#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_NC
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_48
#define AUDIO_I2S_GPIO_WS   GPIO_NUM_15
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_46
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_NC

#define AUDIO_I2S_MIC_GPIO_CLK  GPIO_NUM_44
#define AUDIO_I2S_MIC_GPIO_DATA GPIO_NUM_47

#define IR_TX_PIN            GPIO_NUM_2

#define I2C_SDA_PIN          GPIO_NUM_10
#define I2C_SCL_PIN          GPIO_NUM_11

#define I2C_TOUCH_SDA_PIN    GPIO_NUM_39
#define I2C_TOUCH_SCL_PIN    GPIO_NUM_40

#define AXP2101_ADDR         0x34

#define BOOT_BUTTON_GPIO     GPIO_NUM_0
#define TOUCH_INT_PIN        GPIO_NUM_16

#define DISPLAY_WIDTH   240
#define DISPLAY_HEIGHT  240
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY  false

#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0

#define DISPLAY_SPI_MOSI_PIN GPIO_NUM_13
#define DISPLAY_SPI_SCLK_PIN GPIO_NUM_18
#define DISPLAY_SPI_CS_PIN   GPIO_NUM_12
#define DISPLAY_DC_PIN       GPIO_NUM_38
#define DISPLAY_RST_PIN      GPIO_NUM_NC

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_45
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

#define RADIO_SPI_SCK_PIN   GPIO_NUM_3
#define RADIO_SPI_MISO_PIN  GPIO_NUM_4
#define RADIO_SPI_MOSI_PIN  GPIO_NUM_1
#define RADIO_SPI_CS_PIN    GPIO_NUM_5
#define RADIO_DIO1_PIN      GPIO_NUM_9
#define RADIO_RST_PIN       GPIO_NUM_8
#define RADIO_BUSY_PIN      GPIO_NUM_7

#endif
