#ifndef _CONFIG_H_
#define _CONFIG_H_

#include <driver/gpio.h>

#define BOARD_NAME "T-Embed"

// Display
#define DISPLAY_WIDTH 170
#define DISPLAY_HEIGHT 320
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y true
#define DISPLAY_SWAP_XY false

#define DISPLAY_SPI_MOSI_PIN GPIO_NUM_9
#define DISPLAY_SPI_SCLK_PIN GPIO_NUM_11
#define DISPLAY_SPI_CS_PIN GPIO_NUM_41
#define DISPLAY_DC_PIN GPIO_NUM_16
#define DISPLAY_RST_PIN GPIO_NUM_40
#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_21
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

// Audio
#define AUDIO_INPUT_SAMPLE_RATE 16000
#define AUDIO_OUTPUT_SAMPLE_RATE 16000

#define AUDIO_I2S_MIC_CLK GPIO_NUM_39
#define AUDIO_I2S_MIC_DATA GPIO_NUM_42

#define AUDIO_I2S_SPK_BCLK GPIO_NUM_46
#define AUDIO_I2S_SPK_WS GPIO_NUM_40
#define AUDIO_I2S_SPK_DOUT GPIO_NUM_7

// I2C
#define I2C_SDA_PIN GPIO_NUM_8
#define I2C_SCL_PIN GPIO_NUM_18

// Buttons
#define BOOT_BUTTON_GPIO GPIO_NUM_0
#define USER_BUTTON_GPIO GPIO_NUM_6

#endif // _CONFIG_H_
